### PR TITLE
Webasm [wip, don't yet merge]

### PR DESCRIPTION
**Pull request by runn1ng**
I am leaving this in this repo for now, I will leave it for @szymonlesisz to move it to hd-wallet build :)

### CODE REVIEW

**Comment by prusnak** [comment]
Can you please change segwit option from `bool` to `int` or  even better`enum` with the following options as part of your refactoring?

0 - normal addresses
1 - segwit-in-p2sh addresses

?

Should be backwards compatible and will be ready when other address formats (e.g. native segwit bech32) are introduced.

**Comment by runn1ng** [comment]
:+1: good idea. 

It might confuse current hd-wallet/mytrezor with its API, but, I will need to change the API anyway (I will need to add an API for webasm file loading in the end), so no big deal

**Comment by prusnak** [comment]
> It might confuse current 

how exactly?

**Comment by runn1ng** [comment]
Hm, it probably won't, `true == 1` and `false == 0` (but `true !== 1`), not sure how it will behave in workers.

But it should work fine.

Anyway I will need to change the API anyway, because the wasm needs to be imported by hand - the auto-generated file is found and loaded by heuristics, detecting node/browser/.. by the auto-generated .js file, but the heuristics fail often (in nyc and karma, for example, and breaking the tests)

**Comment by prusnak** [comment]
Whole stuff moved here: https://github.com/trezor/hd-wallet/blob/master/fastxpub

Closing PR and deleting the branch.

**Pull request closed without merging**
