### PR TITLE
Monero: normalization fixes

### PR DESCRIPTION
**Pull request by ph4r05**
PR that came from the discussion with @onvej-sl in https://github.com/trezor/trezor-crypto/pull/169 

Requires rebasing on top of the master and merging https://github.com/trezor/trezor-crypto/pull/171 and https://github.com/trezor/trezor-crypto/pull/172 first.

### CODE REVIEW

**Comment by ph4r05** [comment]
Thanks for the merge guys!

If you could pls rebase this branch on the master - it would be great :) 
PR needs merged changes to scalarmults.

Thanks!

**Comment by prusnak** [comment]
If I get ack from @onvej-sl I'll rebase merge/rebase this in monero branch.

**Comment by ph4r05** [comment]
OK so we need 2 confirmations from @onvej-sl 
- rebase monero branch onto current master with merged PRs fixing scalarmults
- merging this PR 173 into monero branch

Please also consider either https://github.com/trezor/trezor-crypto/pull/174 or https://github.com/trezor/trezor-crypto/pull/175 (or both) because when included together there are macro clashes due to namespace pollution.

**Comment by onvej-sl** [comment]
ACK for rebase, please trigger a travis rebuild than.

**Comment by prusnak** [comment]
Merged #171, #172, #174, #175 into master, rebased monero branch on top of master.

Please rebase this PR. Thank you!

**Comment by ph4r05** [comment]
Thanks! PR rebased, Travis tests are still in queue

**Comment by prusnak** [comment]
@onvej-sl are you OK with the change?

**Comment by onvej-sl** [comment]
ACK

**Comment by prusnak** [comment]
Thank you both!

**Pull request merged**
