### PR TITLE
Ed25519/modm neg, sub added

### PR DESCRIPTION
**Pull request by ph4r05**
Two new operations on ed25519 scalar values (modulo m) were added:
- -x mod m
- x-y mod m

I need this for Monero implementation. I am working another few which I will PR as they are finished and tested.

### CODE REVIEW

**Comment by ph4r05** [comment]
I will further optimize subtraction, reducing the op count.

**Comment by prusnak** [comment]
Have you checked that upstream ed25519-donna doesn't provide these
operations and they indeed need to be created from scratch?

**Comment by ph4r05** [comment]
I've checked:

- https://github.com/floodyberry/ed25519-donna
- https://github.com/agl/curve25519-donna

They don't have constant time subtraction and inversion. The ops are implemented mod p=2^255-19 but not mod order of the generator, which I need for Monero signatures.

I am following the same principle as DJB used for arithmetics mod p + subtraction trick from:  https://www.imperialviolet.org/2010/12/04/ecc.html

Pls wait for the subtraction commit.

**Comment by prusnak** [comment]
> Pls wait for the subtraction commit.

Will do.

**Comment by ph4r05** [comment]
Limb constant computation for the Emilia Kasper trick: https://github.com/ph4r05/monero-agent/blob/master/monero_glue/misc/limbs.py

**Comment by prusnak** [comment]
Nice, is this ready to be merged?

**Comment by ph4r05** [comment]
From my side I think this PR is ready. Thanks!

**Comment by prusnak** [comment]
LGTM Thanks!

**Pull request merged**
