### PR TITLE
bip32, options: optionally exclude 25519 curves in BIP32 support

### PR DESCRIPTION
**Pull request by peter-conalgo**
I wanted to compile without all the 25519 curve stuff, so I had to add this configuration value.

### CODE REVIEW

**Comment by prusnak** [comment]
You should check whether node->curve->params exists in your branch and fail if it does not.

**Comment by peter-conalgo** [comment]
There is basically no support for error handling in this file, so I think it's best for it to fail by dereferencing a null. Could be changed to fail silently, but I don't see that as an improvement.

**Comment by prusnak** [comment]
Fiar

**Comment by peter-conalgo** [comment]
Thanks for the quick merge!

**Pull request merged**
