### PR TITLE
Introduce hex_string() and hex_string_prefixed()

### PR DESCRIPTION
**Pull request by axic**
Perhaps it would make sense having these in a *string utils* file?

Comments welcome

### CODE REVIEW

**Comment by prusnak** [comment]
This won't be needed when we keep address as bytes in messages, right? Or is it just for showing the address on the display?

**Comment by axic** [comment]
It is needed for displaying on screen.

If we remove the space check (and assume the caller takes care of that), this code could also replace the one in sha2: https://github.com/trezor/trezor-crypto/blob/master/sha2.c#L577

Also I think it would make sense changing `hex_string_prefixed()` to be inlined in `hex.h` as it is rather small.

**Comment by prusnak** [comment]
I would rather not add code to trezor-crypto if it's needed just for presentation purposes (i.e. showing on the display). So in case we keep `address` field as `bytes`, let's have it rather in firmware where it belongs, not in crypto library.

Let's see how the RFC discussions finalizes.

**Comment by axic** [comment]
Alright, let's see how it plays out.  I don't mind where it belongs to.  If you consider merging it with the sha2 piece I've linked, then it could go into crypto.

**Comment by jhoenicke** [comment]
Note that the firmware `trezor-mcu` already has the functionality of `hex_string` in `data2hex` in `util.c`.

**Comment by axic** [comment]
@jhoenicke I've missed that - only glimpsed at the `firmware` directory.

Do you think it makes sense adding the `prefixed` version to it?  And maybe an option to toggle between lower/uppercase hex strings?  It can also be solved by running case-changing outside this call.

As a last comment, maybe it is faster having a separate counter for the index in `str` in `data2hex`. Perhaps compilers of today can optimise the current one.

**Pull request closed without merging**
