### PR TITLE
WIP Decred support

### PR DESCRIPTION
**Pull request by peterzen**
Decred specific crypto functions

/cc @saleemrashid - could you please review this code and recommend a better way to generalize `decred_get_address`, `decred_message_sign` and `decred_message_verify`?

### CODE REVIEW

**Comment by saleemrashid** [comment]
@peterzen Since #118 was merged, we don't need any of these functions. For example:

`decred_get_address` is `ecdsa_get_address` with the Decred address version and `HASHER_BLAKE`. 
`decred_message_sign` is `ecdsa_sign` with `HASHER_BLAKE`.
`decred_message_verify` is `ecdsa_verify` with `HASHER_BLAKE`.

**Comment by peterzen** [comment]
`decred_get_address` is slightly different from `ecdsa_get_address`: https://github.com/trezor/trezor-crypto/pull/119/files/74767fbfbef2e82de3ca83c635b1c43183c7358e#diff-5d62e3f1508bedb0c39958a343c14d65R218

Also, `decred_message_sign` signs the message digest – again it's slightly different from `ecdsa_sign`

**Comment by saleemrashid** [comment]
@peterzen What's the difference between `decred_get_address` and `ecdsa_get_address`? Also, `decred_message_sign` is the `cryptoMessageSign` function from https://github.com/trezor/trezor-mcu/blob/master/firmware/crypto.c#L126 but with a `CoinInfo` that uses `secp256k1_decred` instead of `secp256k1`.

**Comment by saleemrashid** [comment]
@peterzen `decred_get_address` isn't calling `hdnode_fill_public_key`.

**Comment by peterzen** [comment]
Right, I did overlook that one, thanks.

**Comment by peterzen** [comment]
This code needs to be moved into `trezor-mcu`

**Pull request closed without merging**
