### PR TITLE
Ed25519-SHA-3 & Ed25519-Keccak Support

### PR DESCRIPTION
**Pull request by saleemrashid**
* Add Ed25519 variants (`_sha3` and `_keccak`)
* Enable `USE_KECCAK` by default
* Added `DONNA_UNUSED` to `ed25519.h` for `curve25519_scalar_product` & `expand256_modm` (`-Werror=unused-function`)
* Added Ruby script to import test vectors from https://github.com/NemProject/nem-test-vectors
* Added test vectors for Keccak-256
* Added test vectors for Ed25519-Keccak
* Added `ed25519_sha3_info` and `ed25519_keccak_info` curves for BIP32 and BIP39
* Constant time verification of `ed25519_keccak` using #96

### CODE REVIEW

**Comment by prusnak** [comment]
Are there any testvectors available so you can add them? Or you would need to generate them?

**Comment by saleemrashid** [comment]
@prusnak I have some for Ed25519-Keccak, ready to add. I don't know if anyone actually uses Ed25519-SHA-3 though, so we might have to generate them. I don't actually need Ed25519-SHA-3, so it could be removed.

**Comment by prusnak** [comment]
My question was whether these vectors come from you or if they are from 3rd party source, so we can do the cross check.

**Comment by saleemrashid** [comment]
@prusnak Ed25519-Keccak: https://github.com/NemProject/nem-test-vectors

**Comment by saleemrashid** [comment]
- [x] Travis CI
- [x] Test vectors for Keccak-256 & Ed25519-Keccak
- [x] Abomination of a Ruby script

@prusnak LGTM.

Not too worried about the lack of Ed25519-SHA-3 test vectors as SHA3-512 vectors and Ed25519-Keccak vectors pass

**Comment by prusnak** [comment]
LGTM. @jhoenicke can you have a look as well?

**Comment by saleemrashid** [comment]
@prusnak @jhoenicke Rebased and added constant-time verification from #96

**Comment by prusnak** [comment]
Merged in https://github.com/trezor/trezor-crypto/commit/d4b5e64ba2ff4426c4c2d3effb5335f71bf67aef

Thanks!

**Pull request closed without merging**
