### PR TITLE
ed25519: aA + bB double scalarmult added

### PR DESCRIPTION
**Pull request by ph4r05**
`a*A + b*B` double scalar multiplication is required for Monero (used in RCT).

I've added a new flag `USE_MONERO` which is by default false. In that case, this added function is not compiled. Is it OK for a generic function in the `ed25519` package or do you want to have it included all the time? I took inspiration from the usage of `ED25519_NO_PRECOMP` flag.

### CODE REVIEW

**Comment by prusnak** [comment]
I like how it is implemented now.

Do you plan to add unit tests? If yes, I'll merge once these have been added.

**Comment by ph4r05** [comment]
ok thanks! I will generate a few testvectors.

**Comment by ph4r05** [comment]
Test vectors added

**Comment by prusnak** [comment]
LGTM merged! Thanks!

**Pull request merged**
