### PR TITLE
Add RC4 Support

### PR DESCRIPTION
**Pull request by saleemrashid**
Includes test vectors from https://tools.ietf.org/html/rfc6229#section-2

/cc @livinginformation

### CODE REVIEW

**Comment by prusnak** [comment]
Who uses RC4 nowadays? Don't tell me it is some cryptocurrency :-(

**Comment by saleemrashid** [comment]
@prusnak Counterparty (just for `OP_RETURN` obfuscation). Should have mentioned that in pull request, but forgot since we had been discussing it on Gitter.

**Comment by prusnak** [comment]
Where is the documentation about how they use it in particular?

I am asking because:

"It is especially vulnerable when the beginning of the output keystream
is not discarded, or when nonrandom or related keys are used."

**Comment by saleemrashid** [comment]
@prusnak It is not used for security. They use the txid of the first UTXO as the key to obfuscate data stored in, e.g., `OP_RETURN` outputs.

Documentation is rather sparse but a search for "Counterparty ARC4" should yield some results.

**Comment by saleemrashid** [comment]
To be honest, I have no idea why they do this for `OP_RETURN` (makes more sense for the old encoding methods). Also, the magic string `CNTRPRTY` is encrypted as well, so it means that they have to run ARC4 on every single transaction which _might_ be a Counterparty transaction.

**Comment by prusnak** [comment]
Lol this is stupid!

**Comment by prusnak** [comment]
Thanks! Merged manually

**Pull request closed without merging**
