### PR TITLE
Add Groestl hash and Groestlcoin (GRS) support

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**

### CODE REVIEW

**Comment by gruve-p** [comment]
Tested on emulator with Electrum-GRS (https://github.com/Groestlcoin/electrum-grs/tree/merge-3-1-2)
Works like a charm! Ack

**Comment by Yokomoko** [comment]
ACK. Reviewed and tested against electrum-grs 3.1.2

**Comment by duudl3** [comment]
Working well on Electrum-GRS (3.1.2). Ack

**Comment by Cold-A-Muse** [comment]
ACK, tested with electrum-grs 3.1.2 and seems to be working fine

**Comment by joenilan** [comment]
ACK. seems to be working fine

**Comment by HAMMERjah** [comment]
Ack

**Comment by yura-pakhuchiy** [comment]
@saleemrashid is it a real ACK or you just mocking previous commenters? :-)

**Comment by saleemrashid** [comment]
@yura-pakhuchiy Both :smile:. Not tested, but it looks :+1:

**Comment by gruve-p** [comment]
Ready for review @prusnak
Bech-32 prefix has been added to https://github.com/satoshilabs/slips/blob/master/slip-0173.md
Electrum-GRS 3.1.2 https://github.com/Groestlcoin/electrum-grs/ has been merged to master with Trezor support

Is this ready to get merged or does it need changes?

**Pull request merged**
